/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    services: Service;
    'case-studies': CaseStudy;
    'team-members': TeamMember;
    practices: Practice;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    practices: PracticesSelect<false> | PracticesSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'pl') | ('en' | 'pl')[];
  globals: {
    'home-page': HomePage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: 'en' | 'pl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Override if needed.
   */
  slug?: string | null;
  /**
   * Used as meta description for SEO (max 160 chars recommended).
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Main image for the post. Used in OG tags and blog listing.
   */
  featuredImage?: (number | null) | Media;
  author?: (number | null) | TeamMember;
  publishedAt: string;
  /**
   * Tags for categorization and related posts.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-calculated from content length.
   */
  readingTime?: number | null;
  /**
   * Overrides the post title in <title> tag and OG. Leave blank to use post title.
   */
  seoTitle?: string | null;
  /**
   * Overrides excerpt for meta description. Leave blank to use excerpt.
   */
  seoDescription?: string | null;
  /**
   * Custom OG image. Falls back to featured image.
   */
  seoOgImage?: (number | null) | Media;
  /**
   * Override canonical URL if this post is cross-posted.
   */
  seoCanonicalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  /**
   * Display order, e.g. "01", "02"
   */
  sortOrder: string;
  name: string;
  role: string;
  /**
   * Profile photo for the team member.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Display order, e.g. "01", "02"
   */
  sortOrder: string;
  /**
   * URL slug for practice subpage, e.g. crm-implementation
   */
  slug?: string | null;
  title: string;
  description: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  /**
   * Display order, e.g. "01", "02"
   */
  sortOrder: string;
  title: string;
  description: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practices".
 */
export interface Practice {
  id: number;
  /**
   * Display order, e.g. "01", "02"
   */
  sortOrder: string;
  /**
   * URL slug for the practice subpage.
   */
  slug: string;
  eyebrow: string;
  headline: {
    text: string;
    accent?: string | null;
  };
  lead: string;
  heroCta?: {
    microCopy?: string | null;
    label?: string | null;
    href?: string | null;
  };
  sections: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  cta: {
    microCopy?: string | null;
    label: string;
    href: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts.
     */
    delete?: boolean | null;
  };
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
  };
  caseStudies?: {
    /**
     * Allow clients to find case-studies.
     */
    find?: boolean | null;
  };
  teamMembers?: {
    /**
     * Allow clients to find team-members.
     */
    find?: boolean | null;
  };
  practices?: {
    /**
     * Allow clients to find practices.
     */
    find?: boolean | null;
  };
  homePage?: {
    /**
     * Allow clients to find home-page global.
     */
    find?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'practices';
        value: number | Practice;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  publishedAt?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  readingTime?: T;
  seoTitle?: T;
  seoDescription?: T;
  seoOgImage?: T;
  seoCanonicalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  sortOrder?: T;
  slug?: T;
  title?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  sortOrder?: T;
  title?: T;
  description?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  sortOrder?: T;
  name?: T;
  role?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "practices_select".
 */
export interface PracticesSelect<T extends boolean = true> {
  sortOrder?: T;
  slug?: T;
  eyebrow?: T;
  headline?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  lead?: T;
  heroCta?:
    | T
    | {
        microCopy?: T;
        label?: T;
        href?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        microCopy?: T;
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  services?:
    | T
    | {
        find?: T;
      };
  caseStudies?:
    | T
    | {
        find?: T;
      };
  teamMembers?:
    | T
    | {
        find?: T;
      };
  practices?:
    | T
    | {
        find?: T;
      };
  homePage?:
    | T
    | {
        find?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  brand: string;
  tagline: string;
  contactEmail: string;
  establishedLine: string;
  version: string;
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  navCta: {
    label: string;
    href: string;
  };
  heroEyebrow: string;
  heroEstablishedLabel?: string | null;
  heroHeadlineLines?:
    | {
        text: string;
        accent?: string | null;
        id?: string | null;
      }[]
    | null;
  heroLead: string;
  heroPrimaryCta: {
    label: string;
    href: string;
  };
  heroSecondaryCta: {
    label: string;
    href: string;
  };
  heroMeta?:
    | {
        label: string;
        value: string;
        logos?:
          | {
              name: string;
              /**
               * Component key from BrandLogos.tsx, e.g. MondayLogo
               */
              component: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  marquee?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  manifestoEyebrow: string;
  manifestoHeadline: {
    text: string;
    accent?: string | null;
  };
  manifestoEntries?:
    | {
        entryId: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  servicesEyebrow: string;
  servicesHeadline: {
    text: string;
    accent?: string | null;
  };
  servicesItems?: (number | Service)[] | null;
  casesEyebrow: string;
  casesHeadline: {
    text: string;
    accent?: string | null;
  };
  casesItems?: (number | CaseStudy)[] | null;
  speedEyebrow: string;
  speedHeadlineLines?:
    | {
        text: string;
        accent?: string | null;
        id?: string | null;
      }[]
    | null;
  speedStats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  processEyebrow: string;
  processHeadline: {
    text: string;
    accent?: string | null;
  };
  processSteps?:
    | {
        stepId: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  partnersEyebrow: string;
  partnersItems?:
    | {
        name: string;
        role: string;
        id?: string | null;
      }[]
    | null;
  teamEyebrow: string;
  teamHeadline: {
    text: string;
    accent?: string | null;
  };
  teamMembers?: (number | TeamMember)[] | null;
  insightsEyebrow: string;
  insightsHeadline: {
    text: string;
    accent?: string | null;
  };
  insightsPosts?:
    | {
        insightId: string;
        category: string;
        date: string;
        title: string;
        id?: string | null;
      }[]
    | null;
  ctaEyebrow: string;
  ctaHeadlineLines?:
    | {
        text: string;
        accent?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaBody: string;
  ctaButton: {
    label: string;
    href: string;
  };
  footerIntro: string;
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerBottom?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  brand?: T;
  tagline?: T;
  contactEmail?: T;
  establishedLine?: T;
  version?: T;
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  navCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroEyebrow?: T;
  heroEstablishedLabel?: T;
  heroHeadlineLines?:
    | T
    | {
        text?: T;
        accent?: T;
        id?: T;
      };
  heroLead?: T;
  heroPrimaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroSecondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroMeta?:
    | T
    | {
        label?: T;
        value?: T;
        logos?:
          | T
          | {
              name?: T;
              component?: T;
              id?: T;
            };
        id?: T;
      };
  marquee?:
    | T
    | {
        label?: T;
        id?: T;
      };
  manifestoEyebrow?: T;
  manifestoHeadline?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  manifestoEntries?:
    | T
    | {
        entryId?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  servicesEyebrow?: T;
  servicesHeadline?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  servicesItems?: T;
  casesEyebrow?: T;
  casesHeadline?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  casesItems?: T;
  speedEyebrow?: T;
  speedHeadlineLines?:
    | T
    | {
        text?: T;
        accent?: T;
        id?: T;
      };
  speedStats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  processEyebrow?: T;
  processHeadline?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  processSteps?:
    | T
    | {
        stepId?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  partnersEyebrow?: T;
  partnersItems?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  teamEyebrow?: T;
  teamHeadline?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  teamMembers?: T;
  insightsEyebrow?: T;
  insightsHeadline?:
    | T
    | {
        text?: T;
        accent?: T;
      };
  insightsPosts?:
    | T
    | {
        insightId?: T;
        category?: T;
        date?: T;
        title?: T;
        id?: T;
      };
  ctaEyebrow?: T;
  ctaHeadlineLines?:
    | T
    | {
        text?: T;
        accent?: T;
        id?: T;
      };
  ctaBody?: T;
  ctaButton?:
    | T
    | {
        label?: T;
        href?: T;
      };
  footerIntro?: T;
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  footerBottom?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}