// importMap.ts — typed wrapper for the auto-generated importMap.js
// importMap.js is generated by Payload CMS during next build/dev.
// TypeScript cannot import .js directly (allowJs: false), so we cast the empty
// object here as the correct type. At runtime, Payload's build system replaces
// importMap.js with the actual component map.
import type { ImportMap } from "payload";

export const importMap: ImportMap = {} as ImportMap;
